### ISSUE TITLE
exported format

### ISSUE THREAD

**Issue by kaktux** [michaelx/bye-bye-feedly#1]
hi there,

export works fine - but it would be even nicer to have a file as result that can be imported into other readers instead of the current solution.
I basically used it to get all my read later articles out of feedly -which probably most would use it for. So a more common format - because the current one isn't readable by all of the programs i tried (browsers, readlater apps)

**Comment by michaelx** [comment]
This isn’t really the scope of this project, as the export format is already JSON, which is universal. Based on that you could write a data transformer to make it work with the feed reader you’d like to use. However most feed readers just allow you to import the list of feeds you’re subscribed to, but not the posts/favs itself. Actually I don’t know a single one that allows that, which was the reason for bye-bye-feedly. Sorry about that, if you find a reader that supports the import of posts/favs let me know.
